# Generated by Django 4.2.23 on 2025-09-03 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_downloaded_counter', models.PositiveIntegerField(default=0)),
                ('ai_requests_counter', models.PositiveIntegerField(default=0)),
                ('tasks_generated_counter', models.PositiveIntegerField(default=0)),
                ('sections_generated_counter', models.PositiveIntegerField(default=0)),
                ('lessons_generated_counter', models.PositiveIntegerField(default=0)),
                ('first_activity_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
