# Generated by Django 4.2.23 on 2025-09-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArseniyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100, verbose_name='Имя ребёнка')),
                ('grade', models.CharField(max_length=20, verbose_name='Класс')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
