# Generated by Django 4.2.23 on 2025-08-30 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontextlength',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context_length', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userautogenerationpreferences',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autogeneration_preferences', to='hub.course'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='hub.classroom'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='hub.basetask'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hub.lesson'),
        ),
        migrations.AddIndex(
            model_name='savedunsplashimage',
            index=models.Index(fields=['query'], name='hub_savedun_query_900461_idx'),
        ),
        migrations.AddIndex(
            model_name='savedunsplashimage',
            index=models.Index(fields=['-created_at'], name='hub_savedun_created_012dc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedunsplashimage',
            unique_together={('query', 'url')},
        ),
        migrations.AddField(
            model_name='mediafile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonpublicdata',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_data', to='hub.lesson'),
        ),
        migrations.AddField(
            model_name='lessongenerationstatus',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hub.lesson'),
        ),
        migrations.AddField(
            model_name='lessongenerationstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_generations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='hub.course'),
        ),
        migrations.AddField(
            model_name='homework',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Назначено учителем'),
        ),
        migrations.AddField(
            model_name='homework',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='hub.classroom', verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='hub.lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='homework',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='homeworks', to='hub.basetask', verbose_name='Задания'),
        ),
        migrations.AddField(
            model_name='generation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursepdf',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='hub.course'),
        ),
        migrations.AddField(
            model_name='coursepdf',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_pdfs', to='hub.mediafile'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='hub.lesson'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role__in': ['student', 'teacher']}, related_name='classrooms_as_student', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'teacher'}, related_name='classrooms_as_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учителя'),
        ),
        migrations.AddField(
            model_name='basetask',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='basetask',
            name='media',
            field=models.ManyToManyField(blank=True, to='hub.mediafile'),
        ),
        migrations.AddField(
            model_name='basetask',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_tasks', to='hub.section'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('classroom', 'task', 'user')},
        ),
    ]
