# Generated by Django 4.2.23 on 2025-08-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonpublicdata',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_pdfs/', verbose_name='PDF файл'),
        ),
    ]
