# Generated by Django 4.2.23 on 2025-09-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_lessonpublicdata_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLessonsEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email пользователя')),
                ('allow_emails', models.BooleanField(default=True, verbose_name='Разрешить рассылки')),
            ],
            options={
                'verbose_name': 'Email для рассылок',
                'verbose_name_plural': 'Email-адреса для рассылок',
            },
        ),
    ]
