# Generated by Django 4.2.23 on 2025-09-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_publiclessonsemails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
    ]
