# Generated by Django 4.2.23 on 2025-09-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_section_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('tutor', 'Частный репетитор'), ('school_teacher', 'Школьный учитель'), ('university_teacher', 'Преподаватель вуза'), ('other', 'Другое')], max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('tg_homework', models.CharField(choices=[('yes', 'Да'), ('maybeyes', 'Скорее да'), ('maybe', 'Скорее нет'), ('no', 'Точно нет')], max_length=10)),
                ('ai_checking', models.CharField(choices=[('yes', 'Да'), ('maybeyes', 'Скорее да'), ('maybe', 'Скорее нет'), ('no', 'Точно нет')], max_length=10)),
                ('workflow', models.TextField(blank=True, null=True)),
                ('tester', models.BooleanField(default=False)),
            ],
        ),
    ]
