# Generated by Django 4.2.23 on 2025-09-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
